// Chinese name labels for glossary terms. The canonical (usually English)
// technical term stays as the primary label; this adds the Chinese name beside it
// (e.g. "Linear blend skinning · 线性混合蒙皮"). Definitions are bilingual already
// (see glossaryTerms.ts); this only labels the term *names*. Keyed by the exact
// term string; lookups also try a lowercased fallback.
export const termLabelsZh: Record<string, string> = {
  // — Foundations —
  mesh: "网格",
  vertex: "顶点",
  voxel: "体素",
  tensor: "张量",
  MLP: "多层感知机",
  "neural network": "神经网络",
  backbone: "主干网络",
  gradient: "梯度",
  backpropagation: "反向传播",
  differentiable: "可微",
  loss: "损失",
  regularization: "正则化",
  prior: "先验",
  "inductive bias": "归纳偏置",
  manifold: "流形",
  ray: "光线",
  pixel: "像素",
  "depth map": "深度图",
  "point cloud": "点云",
  blendshape: "混合形状",
  latent: "潜变量",
  embedding: "嵌入",
  transformer: "变换器",
  attention: "注意力",
  convolution: "卷积",
  RNN: "循环神经网络",
  softmax: "归一化指数函数",
  argmax: "最大值索引",
  VAE: "变分自编码器",
  diffusion: "扩散模型",
  "self-supervised": "自监督",
  ablation: "消融实验",
  PCA: "主成分分析",
  SVD: "奇异值分解",
  "least squares": "最小二乘",
  "homogeneous coordinates": "齐次坐标",
  quaternion: "四元数",
  "Euler angles": "欧拉角",
  rasterization: "光栅化",
  "alpha compositing": "透明度合成",
  keyframe: "关键帧",
  odometry: "里程计",
  occlusion: "遮挡",
  saliency: "显著性",
  foveated: "中心凹",

  // — Track key terms —
  "4D reconstruction": "四维重建",
  "6D rotation": "6D 旋转表示",
  Ablation: "消融实验",
  "Action grammar": "动作语法",
  "Action grammar / script": "动作语法 / 脚本",
  "Active object": "活动物体",
  "Adaptive densification": "自适应稠密化",
  "Adversarial pose prior": "对抗式姿态先验",
  Affordance: "可供性",
  Anticipation: "动作预判",
  "Bayesian label fusion": "贝叶斯标签融合",
  "Bundle adjustment": "光束法平差",
  "Canonical + deformation": "规范空间 + 形变",
  "Contact state": "接触状态",
  "Differentiable volume rendering": "可微体渲染",
  Drift: "漂移",
  "Egocentric / exocentric": "第一视角 / 第三视角",
  Embodiment: "具身",
  "Epipolar constraint": "对极约束",
  "Explicit primitive": "显式基元",
  "Explicit vs implicit capacity": "显式 vs 隐式表达能力",
  "Eye–hand coordination": "手眼协调",
  "Failure-mode analysis": "失败模式分析",
  Floaters: "漂浮伪影",
  "Gimbal lock": "万向锁",
  "Goal inference": "目标推断",
  "Hand ownership": "手部归属",
  "Heatmap regression": "热图回归",
  "Hierarchical organization": "层级组织",
  "Honest baseline": "诚实基线",
  "Implicit field": "隐式场",
  Integration: "积分",
  "Intrinsics / extrinsics": "内参 / 外参",
  Lifting: "二维到三维提升",
  "Linear blend skinning": "线性混合蒙皮",
  "Loop closure": "回环检测",
  "MANO / FLAME": "手 / 脸参数模型",
  "Motion diffusion": "运动扩散",
  "Motion prior": "运动先验",
  "Motion representation": "运动表示",
  "Multi-resolution hash grid": "多分辨率哈希网格",
  "Multimodal annotation (Xperience-10M)": "多模态标注（Xperience-10M）",
  "Neural / dense SLAM": "神经 / 稠密 SLAM",
  "Non-penetration": "非穿透约束",
  "Object-centric": "以物体为中心",
  "Open-vocabulary mapping": "开放词表建图",
  "Perception–prediction–planning–action": "感知—预测—规划—行动",
  PnP: "透视 n 点定位",
  "Point of regard / gaze": "注视点 / 视线",
  "Projection ambiguity": "投影歧义",
  "Radiance field": "辐射场",
  "Reference frame": "参考系",
  "Representation→reasoning": "表示→推理",
  "Reprojection loss": "重投影损失",
  "SDF / level-set": "符号距离场 / 水平集",
  "SMPL-X": "SMPL-X 参数化人体",
  SMPLify: "SMPLify 拟合",
  "Scene graph": "场景图",
  "Self-occlusion": "自遮挡",
  "Shape β / pose θ": "体型 β / 姿态 θ",
  "Space-centric": "以空间为中心",
  "Spatio-temporal graph": "时空图",
  Splatting: "泼溅",
  Submap: "子地图",
  "TSDF fusion": "TSDF 融合",
  "Top-k anticipation": "Top-k 预判",
  Triangulation: "三角化",
  "Tube masking": "管状掩码",
  "Two-stream / SlowFast": "双流 / SlowFast",
  "Verb–noun action": "动词—名词动作",
  "Visual odometry": "视觉里程计",
  "World memory": "世界记忆",
  "World model": "世界模型",
};

// Look up a term's Chinese name (exact, then case-insensitive).
export function zhLabel(term: string): string | undefined {
  return termLabelsZh[term] ?? termLabelsZh[term.toLowerCase()];
}
