// AUTO-GENERATED by scripts/gen-outputs.mjs from the executed notebooks.
// Each lesson's runnable snippet output: printed stdout + whether a figure
// (public/code-output/<id>.png) exists. Shown inline on the lesson page.
export const codeOutputs: Record<string, { stdout: string; image: boolean }> = {
  "A1": {
    "stdout": "params per body: 25 -> mesh vertices: 200",
    "image": true
  },
  "A2": {
    "stdout": "2D keypoints: (12, 2) -> lifted 3D: (12, 3)",
    "image": true
  },
  "A3": {
    "stdout": "velocity is translation-invariant: True\ntemporal-conv motion feature: (1, 64)",
    "image": true
  },
  "A4": {
    "stdout": "trained from 2D keypoints only; final loss: 0.019",
    "image": true
  },
  "A5": {
    "stdout": "SMPL-X verts: 540 | hand-object contact dist: 1.016",
    "image": true
  },
  "A6": {
    "stdout": "orthonormal: True | det=+1: True",
    "image": true
  },
  "A7": {
    "stdout": "generated motion: (1, 144) conditioned on (1, 16)",
    "image": true
  },
  "A8": {
    "stdout": "vertices still penetrating: 0",
    "image": true
  },
  "A9": {
    "stdout": "final reproj  with prior=0.0000  no prior=0.0000",
    "image": true
  },
  "B1": {
    "stdout": "all 6 depths -> same pixel: True",
    "image": true
  },
  "B2": {
    "stdout": "triangulation error: 0.0",
    "image": true
  },
  "B3": {
    "stdout": "final reprojection error: 0.0",
    "image": true
  },
  "B4": {
    "stdout": "MLP learned the SDF, residual: 0.017",
    "image": true
  },
  "B5": {
    "stdout": "rendered pixel RGB: [0.014999999664723873, 0.01600000075995922, 0.013000000268220901]",
    "image": true
  },
  "B6": {
    "stdout": "feature dim per point: 8 (read by a tiny MLP)",
    "image": true
  },
  "B7": {
    "stdout": "rasterized center pixel: [0.20999999344348907, 0.5899999737739563, 0.3400000035762787]",
    "image": true
  },
  "B8": {
    "stdout": "appearance shared across time; only the deformation field varies",
    "image": true
  },
  "B9": {
    "stdout": "final photometric loss: 0.0017",
    "image": true
  },
  "C1": {
    "stdout": "ego-motion magnitude (proxy for where you look): 0.332",
    "image": true
  },
  "C2": {
    "stdout": "most common: [('take:onion', 23), ('take:knife', 21), ('cut:onion', 21)] | singletons: 0\nparticipant-held-out split: train=202 test=98",
    "image": true
  },
  "C3": {
    "stdout": "SlowFast fused feature: (1, 64, 4, 56, 56) | masked 90% of patches",
    "image": true
  },
  "C4": {
    "stdout": "recognized (verb,noun): (4, 4)\ntop-5 next actions: [1, 6, 2, 15, 19] | true in top-5: False",
    "image": true
  },
  "C5": {
    "stdout": "x= 40 side=left  own=True\nx=430 side=right own=True\nx=260 side=left  own=False",
    "image": true
  },
  "C6": {
    "stdout": "contact (IoU): {'knife': 0.053, 'plate': 0.0, 'cup': 0.056} -> active object: cup",
    "image": true
  },
  "C7": {
    "stdout": "gaze-attended feature: (64,) | gaze leads hand by 4 frames",
    "image": true
  },
  "C8": {
    "stdout": "after {'grind'} valid next: ['add_water', 'add_milk'] | inferred goal: latte",
    "image": true
  },
  "C9": {
    "stdout": "top-1=1.00 top-5=1.00 | shuffled control=0.05 (~chance 0.05)",
    "image": true
  },
  "D1": {
    "stdout": "drift at loop end: 0.135 -> after loop closure: 0.0",
    "image": true
  },
  "D2": {
    "stdout": "recovered translation: [0.30000001192092896, -0.20000000298023224, 0.10000000149011612] | true: [0.30000001192092896, -0.20000000298023224, 0.10000000149011612]",
    "image": true
  },
  "D3": {
    "stdout": "fused surface depth: [1.] (true 1.0)",
    "image": true
  },
  "D4": {
    "stdout": "fused posterior: [0.0, 0.0, 1.0, 0.0] -> argmax 2\nopen-vocab best match: element 3",
    "image": true
  },
  "D5": {
    "stdout": "is the mug in the kitchen?: True\nwhat is on the table?: ['mug', 'kettle']",
    "image": true
  },
  "D6": {
    "stdout": "space query - stand at (5,5)?: True | object query - graspable: ['mug']",
    "image": true
  },
  "D7": {
    "stdout": "in the chair's frame the point is to its right",
    "image": true
  },
  "D8": {
    "stdout": "best imagined return: -0.4 among 24 rollouts",
    "image": true
  },
  "D9": {
    "stdout": "object in kitchen?: True",
    "image": true
  }
};
