import type { McqItem } from "../types";

// One auto-gradable MCQ per lesson — a fast retrieval check that COMPLEMENTS the
// open-ended "Check yourself" cards (it deliberately targets a different facet of
// the lesson, usually a term/definition, so the two never duplicate). Feeds the
// per-track quiz. `correct` indexes into `options` (varied, not always first).
export const lessonQuiz: Record<string, McqItem> = {
  // ── Track A ────────────────────────────────────────────────────────────────
  A1: {
    id: "A1-mcq",
    prompt: { en: "In SMPL, what does linear blend skinning (LBS) do?", zh: "在 SMPL 中，线性混合蒙皮（LBS）做什么？" },
    options: [
      { en: "Stores a class label per vertex", zh: "为每个顶点存储类别标签" },
      { en: "Deforms the mesh by blending bone transforms per vertex", zh: "通过逐顶点混合骨骼变换来形变网格" },
      { en: "Renders the body to a 2D image", zh: "把身体渲染成 2D 图像" },
      { en: "Estimates the camera pose", zh: "估计相机位姿" },
    ],
    correct: 1,
    explain: { en: "As the skeleton moves, LBS rotates each vertex by a blend of nearby bone transforms — the skinning step that poses the template mesh.", zh: "随骨架运动，LBS 用附近骨骼变换的混合来旋转每个顶点——给模板网格摆姿态的蒙皮步骤。" },
  },
  A2: {
    id: "A2-mcq",
    prompt: { en: "In 3D pose estimation, what does ‘lifting’ mean?", zh: "在三维姿态估计中，「抬升（lifting）」指什么？" },
    options: [
      { en: "Predicting 3D joints from detected 2D keypoints using body priors", zh: "借助身体先验，从检测到的 2D 关键点预测 3D 关节" },
      { en: "Increasing the image resolution", zh: "提高图像分辨率" },
      { en: "Cropping the person from the background", zh: "把人从背景中裁出" },
      { en: "Averaging joint positions over time", zh: "对关节位置随时间求平均" },
    ],
    correct: 0,
    explain: { en: "Lifting infers 3D joint positions from 2D keypoints, leaning on learned priors about plausible human bodies to resolve depth.", zh: "抬升从 2D 关键点推断 3D 关节位置，依靠关于合理人体的学到先验来消解深度。" },
  },
  A3: {
    id: "A3-mcq",
    prompt: { en: "A spatio-temporal graph network (ST-GCN) models the skeleton as…", zh: "时空图网络（ST-GCN）把骨架建模为……" },
    options: [
      { en: "A single static RGB image", zh: "一张静态 RGB 图像" },
      { en: "A flat list of pixel colors", zh: "一串扁平的像素颜色" },
      { en: "A graph of joints (bone edges) evolving over time", zh: "一张随时间演化的关节（骨边）图" },
      { en: "A camera calibration matrix", zh: "一个相机标定矩阵" },
    ],
    correct: 2,
    explain: { en: "ST-GCN treats the skeleton as a graph and propagates information across both space (connected joints) and time (frames).", zh: "ST-GCN 把骨架当作图，在空间（相连关节）与时间（帧）两方向传播信息。" },
  },
  A4: {
    id: "A4-mcq",
    prompt: { en: "What is the ‘adversarial pose prior’ in HMR?", zh: "HMR 中的「对抗姿态先验」是什么？" },
    options: [
      { en: "A depth-sensor reading", zh: "一次深度传感器读数" },
      { en: "A second calibrated camera", zh: "第二台已标定相机" },
      { en: "A text caption of the action", zh: "动作的文字描述" },
      { en: "A discriminator that pushes predicted poses to look like real ones", zh: "一个判别器，推动预测姿态看起来像真实姿态" },
    ],
    correct: 3,
    explain: { en: "A discriminator learns to tell real poses from predicted ones; the regressor is pushed to fool it, keeping outputs on the manifold of realistic poses.", zh: "判别器学习区分真实与预测姿态；回归器被推动去骗过它，使输出保持在真实姿态的流形上。" },
  },
  A5: {
    id: "A5-mcq",
    prompt: { en: "MANO models the ___ and FLAME models the ___.", zh: "MANO 建模___，FLAME 建模___。" },
    options: [
      { en: "hand / face", zh: "手 / 面部" },
      { en: "leg / torso", zh: "腿 / 躯干" },
      { en: "camera / lighting", zh: "相机 / 光照" },
      { en: "floor / wall", zh: "地面 / 墙壁" },
    ],
    correct: 0,
    explain: { en: "MANO is the parametric hand model and FLAME the face/head model; with SMPL they compose into the full-body SMPL-X.", zh: "MANO 是参数化手部模型，FLAME 是面部/头部模型；与 SMPL 一起组成全身的 SMPL-X。" },
  },
  A6: {
    id: "A6-mcq",
    prompt: { en: "‘Gimbal lock’ refers to…", zh: "「万向锁」指的是……" },
    options: [
      { en: "A GPU out-of-memory error", zh: "GPU 显存溢出错误" },
      { en: "Loss of a rotational degree of freedom in Euler-angle representations", zh: "欧拉角表示中旋转自由度的丢失" },
      { en: "A kind of linear blend skinning", zh: "一种线性混合蒙皮" },
      { en: "A camera lens distortion", zh: "一种相机镜头畸变" },
    ],
    correct: 1,
    explain: { en: "When two Euler axes align, one rotational DOF is lost — one source of the discontinuities that make Euler angles hard to regress.", zh: "当两个欧拉轴对齐时，丢失一个旋转自由度——这是使欧拉角难以回归的不连续来源之一。" },
  },
  A7: {
    id: "A7-mcq",
    prompt: { en: "A motion diffusion model generates a sequence by…", zh: "运动扩散模型生成序列的方式是……" },
    options: [
      { en: "A single feed-forward pass", zh: "一次前馈" },
      { en: "Nearest-neighbor lookup in the dataset", zh: "在数据集中做最近邻查找" },
      { en: "Iteratively denoising a noisy sequence into a coherent one", zh: "迭代地把含噪序列去噪成连贯序列" },
      { en: "Solving bundle adjustment", zh: "求解光束法平差" },
    ],
    correct: 2,
    explain: { en: "Like image diffusion, it starts from noise and applies many learned denoising steps (optionally conditioned on text) to produce motion.", zh: "与图像扩散一样，它从噪声出发，应用许多学到的去噪步骤（可按文本为条件）来产出运动。" },
  },
  A8: {
    id: "A8-mcq",
    prompt: { en: "The ‘non-penetration’ constraint states that…", zh: "「非穿插」约束规定……" },
    options: [
      { en: "The body and scene meshes may not overlap in 3D", zh: "身体与场景网格在 3D 中不得重叠" },
      { en: "The camera may not move", zh: "相机不得移动" },
      { en: "Labels may not change over time", zh: "标签不得随时间改变" },
      { en: "Viewing rays must stay parallel", zh: "视线必须保持平行" },
    ],
    correct: 0,
    explain: { en: "Solid bodies can't pass through objects; enforcing non-penetration (plus support/contact) pins down otherwise-ambiguous 3D placement.", zh: "实体不能穿过物体；强制非穿插（加支撑/接触）固定了原本歧义的 3D 摆放。" },
  },
  A9: {
    id: "A9-mcq",
    prompt: { en: "SMPLify fits a body to an image by…", zh: "SMPLify 把身体拟合到图像的方式是……" },
    options: [
      { en: "Training a CNN end-to-end on millions of images", zh: "在数百万图像上端到端训练 CNN" },
      { en: "Rendering a NeRF of the scene", zh: "渲染场景的 NeRF" },
      { en: "Running loop closure", zh: "运行回环闭合" },
      { en: "Optimizing SMPL params to minimize reprojection + a pose prior", zh: "优化 SMPL 参数以最小化重投影 + 姿态先验" },
    ],
    correct: 3,
    explain: { en: "SMPLify is optimization-based: for one clip it directly minimizes 2D reprojection plus a pose prior — no training loop needed.", zh: "SMPLify 基于优化：对一段片段直接最小化 2D 重投影加姿态先验——无需训练循环。" },
  },

  // ── Track B ────────────────────────────────────────────────────────────────
  B1: {
    id: "B1-mcq",
    prompt: { en: "The camera intrinsics matrix K encodes…", zh: "相机内参矩阵 K 编码……" },
    options: [
      { en: "Focal length and principal point", zh: "焦距与主点" },
      { en: "The camera's position in the world", zh: "相机在世界中的位置" },
      { en: "The 3D scene points", zh: "场景的 3D 点" },
      { en: "The scene lighting", zh: "场景光照" },
    ],
    correct: 0,
    explain: { en: "K holds the camera's internal optics (focal length, principal point); where the camera sits and looks is the extrinsics [R|t].", zh: "K 保存相机内部光学（焦距、主点）；相机在哪、朝哪看是外参 [R|t]。" },
  },
  B2: {
    id: "B2-mcq",
    prompt: { en: "Triangulation recovers a 3D point by…", zh: "三角测量恢复 3D 点的方式是……" },
    options: [
      { en: "Reading depth directly from a single image", zh: "直接从单张图像读取深度" },
      { en: "Intersecting the two viewing rays from corresponding pixels", zh: "让对应像素的两条视线相交" },
      { en: "Averaging the two images' colors", zh: "对两图的颜色求平均" },
      { en: "Masking spatio-temporal patches", zh: "掩盖时空块" },
    ],
    correct: 1,
    explain: { en: "Given a correspondence and both camera poses, the two back-projected rays meet at the point's 3D location (least squares under noise).", zh: "给定一对对应与两相机位姿，两条反投影射线交于该点的 3D 位置（含噪时按最小二乘）。" },
  },
  B3: {
    id: "B3-mcq",
    prompt: { en: "PnP (Perspective-n-Point) solves for…", zh: "PnP（n 点透视）求解……" },
    options: [
      { en: "A camera's pose from known 3D↔2D correspondences", zh: "由已知 3D↔2D 对应求相机位姿" },
      { en: "The 3D points from a single image", zh: "由单张图像求 3D 点" },
      { en: "The focal length only", zh: "仅求焦距" },
      { en: "The scene lighting", zh: "场景光照" },
    ],
    correct: 0,
    explain: { en: "PnP localizes one camera given known 3D points and their 2D projections — the per-frame tracking step inside SfM/SLAM.", zh: "PnP 在已知 3D 点及其 2D 投影下定位单个相机——SfM/SLAM 内逐帧跟踪的步骤。" },
  },
  B4: {
    id: "B4-mcq",
    prompt: { en: "In a signed distance function, a point INSIDE the surface has…", zh: "在符号距离函数中，曲面内部的点其值……" },
    options: [
      { en: "A positive value", zh: "为正" },
      { en: "Always exactly zero", zh: "总是恰好为零" },
      { en: "A negative value", zh: "为负" },
      { en: "An undefined value", zh: "未定义" },
    ],
    correct: 2,
    explain: { en: "An SDF is negative inside, positive outside, and zero on the surface (the zero level-set); its gradient gives the surface normal.", zh: "SDF 内部为负、外部为正、表面为零（零等值面）；其梯度给出表面法向。" },
  },
  B5: {
    id: "B5-mcq",
    prompt: { en: "A NeRF MLP maps (3D position, view direction) to…", zh: "NeRF 的 MLP 把（3D 位置，视线方向）映射到……" },
    options: [
      { en: "A class label", zh: "类别标签" },
      { en: "Color and volume density", zh: "颜色与体密度" },
      { en: "A camera pose", zh: "相机位姿" },
      { en: "A triangle mesh", zh: "三角网格" },
    ],
    correct: 1,
    explain: { en: "NeRF is a radiance field (x, d) → (c, σ); pixels render by integrating color weighted by density and transmittance along the ray.", zh: "NeRF 是辐射场 (x, d) → (c, σ)；像素由沿射线按密度与透射率加权积分颜色得到。" },
  },
  B6: {
    id: "B6-mcq",
    prompt: { en: "In Instant-NGP, the interpolated hash-grid features are fed to…", zh: "在 Instant-NGP 中，插值后的哈希网格特征被喂给……" },
    options: [
      { en: "A tiny MLP", zh: "一个极小的 MLP" },
      { en: "A very large MLP", zh: "一个非常大的 MLP" },
      { en: "A transformer", zh: "一个 transformer" },
      { en: "No network at all", zh: "完全不用网络" },
    ],
    correct: 0,
    explain: { en: "Most capacity lives in the explicit grid, so only a tiny MLP decodes the looked-up features — which is why it trains in seconds.", zh: "大部分容量在显式网格里，故只需极小 MLP 解码查到的特征——这正是它以秒计训练的原因。" },
  },
  B7: {
    id: "B7-mcq",
    prompt: { en: "3D Gaussian Splatting renders the scene by…", zh: "三维高斯泼溅渲染场景的方式是……" },
    options: [
      { en: "Ray-marching an implicit MLP", zh: "对隐式 MLP 做射线行进" },
      { en: "Running bundle adjustment", zh: "运行光束法平差" },
      { en: "Marching cubes on a voxel grid", zh: "在体素网格上做 marching cubes" },
      { en: "Rasterizing and alpha-blending the Gaussians", zh: "光栅化并 alpha 混合这些高斯" },
    ],
    correct: 3,
    explain: { en: "Each Gaussian is splatted to the image and alpha-blended by a fast differentiable rasterizer — far cheaper than NeRF's volume integration.", zh: "每个高斯被泼溅到图像并经快速可微光栅化器 alpha 混合——远比 NeRF 的体积分便宜。" },
  },
  B8: {
    id: "B8-mcq",
    prompt: { en: "A ‘4D’ reconstruction represents…", zh: "「4D」重建表示……" },
    options: [
      { en: "Time-varying 3D geometry (3D + time)", zh: "随时间变化的 3D 几何（3D + 时间）" },
      { en: "Four synchronized cameras", zh: "四台同步相机" },
      { en: "A 4-layer neural network", zh: "一个 4 层神经网络" },
      { en: "RGBA (color + alpha)", zh: "RGBA（颜色 + 透明度）" },
    ],
    correct: 0,
    explain: { en: "4D = 3D + time: a canonical 3D shape plus a deformation field that warps it across frames.", zh: "4D = 3D + 时间：一个标准 3D 形状加一个跨帧扭曲它的形变场。" },
  },
  B9: {
    id: "B9-mcq",
    prompt: { en: "‘Adaptive densification’ in 3DGS means…", zh: "3DGS 中的「自适应稠密化」指……" },
    options: [
      { en: "Deleting all the Gaussians", zh: "删除所有高斯" },
      { en: "Freezing the MLP weights", zh: "冻结 MLP 权重" },
      { en: "Adding Gaussians where reconstruction error is high", zh: "在重建误差高处增加高斯" },
      { en: "Doubling the image resolution", zh: "把图像分辨率翻倍" },
    ],
    correct: 2,
    explain: { en: "It grows Gaussians where the scene needs detail (high error/gradient) and prunes wasted ones, matching capacity to scene complexity.", zh: "它在场景需要细节处（高误差/梯度）增生高斯、剪除浪费的，使容量匹配场景复杂度。" },
  },

  // ── Track C ────────────────────────────────────────────────────────────────
  C1: {
    id: "C1-mcq",
    prompt: { en: "‘Exocentric’ video refers to…", zh: "「第三人称（exocentric）」视频指……" },
    options: [
      { en: "A head-mounted, first-person camera", zh: "头戴的第一人称相机" },
      { en: "A third-person / external camera view", zh: "第三人称/外部相机视角" },
      { en: "A depth sensor", zh: "深度传感器" },
      { en: "A thermal camera", zh: "热成像相机" },
    ],
    correct: 1,
    explain: { en: "Exocentric = third-person, the external viewpoint most datasets use; egocentric is the head-worn, first-person view.", zh: "Exocentric = 第三人称，大多数数据集采用的外部视角；egocentric 是头戴的第一人称视角。" },
  },
  C2: {
    id: "C2-mcq",
    prompt: { en: "Which dataset pairs egocentric video with synchronized eye-tracking?", zh: "哪个数据集把第一人称视频与同步眼动追踪配对？" },
    options: [
      { en: "EGTEA Gaze+", zh: "EGTEA Gaze+" },
      { en: "EPIC-Kitchens", zh: "EPIC-Kitchens" },
      { en: "Ego4D", zh: "Ego4D" },
      { en: "ImageNet", zh: "ImageNet" },
    ],
    correct: 0,
    explain: { en: "EGTEA Gaze+ provides synchronized gaze, making it the go-to benchmark for gaze-conditioned recognition.", zh: "EGTEA Gaze+ 提供同步注视，是注视条件识别的首选基准。" },
  },
  C3: {
    id: "C3-mcq",
    prompt: { en: "‘Tube masking’ (VideoMAE) hides…", zh: "「管状掩码」（VideoMAE）遮挡……" },
    options: [
      { en: "Random pixels within a single frame", zh: "单帧内的随机像素" },
      { en: "The audio track", zh: "音轨" },
      { en: "The action labels", zh: "动作标签" },
      { en: "The same spatial patch across all frames", zh: "在所有帧上遮挡同一空间块" },
    ],
    correct: 3,
    explain: { en: "Masking a patch through time (a tube) stops the model copying it from a neighboring frame, forcing it to learn real motion.", zh: "沿时间遮挡一个块（一条管）阻止模型从相邻帧复制它，迫使其学习真实运动。" },
  },
  C4: {
    id: "C4-mcq",
    prompt: { en: "Action anticipation predicts the next action using…", zh: "动作预判预测下一动作所用的是……" },
    options: [
      { en: "Only the video before the action begins", zh: "仅动作开始之前的视频" },
      { en: "The full clip including the action", zh: "包含动作的完整片段" },
      { en: "The audio track only", zh: "仅音轨" },
      { en: "The very last frame", zh: "最后一帧" },
    ],
    correct: 0,
    explain: { en: "Anticipation forecasts an action τ seconds ahead from only the preceding video — strictly harder than recognizing an observed action.", zh: "预判仅凭之前的视频预测 τ 秒后的动作——严格地比识别已观测动作更难。" },
  },
  C5: {
    id: "C5-mcq",
    prompt: { en: "‘Hand ownership’ means distinguishing…", zh: "「手的归属」指区分……" },
    options: [
      { en: "Left hand from right hand", zh: "左手与右手" },
      { en: "Open hand from closed fist", zh: "张开的手与握拳" },
      { en: "The wearer's own hands from other people's hands", zh: "佩戴者自己的手与他人的手" },
      { en: "Near hands from far hands", zh: "近处的手与远处的手" },
    ],
    correct: 2,
    explain: { en: "In social/instructional video both the wearer's and others' hands appear; ownership separates ‘what I'm doing’ from ‘what I'm being shown’.", zh: "在社交/教学视频里，佩戴者与他人的手都会出现；归属区分「我在做什么」与「别人在示范什么」。" },
  },
  C6: {
    id: "C6-mcq",
    prompt: { en: "A ‘contact state’ signal is used to…", zh: "「接触状态」信号用于……" },
    options: [
      { en: "Segment video into interaction episodes (hand touching object)", zh: "把视频切分为交互片段（手触碰物体）" },
      { en: "Label the room type", zh: "标注房间类型" },
      { en: "Track the camera pose", zh: "跟踪相机位姿" },
      { en: "Count the people present", zh: "统计在场人数" },
    ],
    correct: 0,
    explain: { en: "Contact onset/offset marks where a manipulation begins and ends, turning a continuous stream into discrete action units.", zh: "接触的开始/结束标记操作的起止，把连续流变成离散动作单元。" },
  },
  C7: {
    id: "C7-mcq",
    prompt: { en: "The 2D location in the frame where the eye is fixating is called the…", zh: "眼睛在画面中注视的 2D 位置称为……" },
    options: [
      { en: "Principal point", zh: "主点" },
      { en: "Epipole", zh: "对极点" },
      { en: "Point of regard (gaze point)", zh: "注视点（point of regard）" },
      { en: "Active object", zh: "活动物体" },
    ],
    correct: 2,
    explain: { en: "The point of regard is the foveated 2D location — the clean attention signal egocentric models exploit; an eye tracker measures it, or it's predicted from the frame.", zh: "注视点是中央凹的 2D 位置——第一人称模型利用的干净注意力信号；由眼动仪测得或从画面预测。" },
  },
  C8: {
    id: "C8-mcq",
    prompt: { en: "An ‘action grammar’ encodes…", zh: "「动作语法」编码……" },
    options: [
      { en: "The pixel colors of each frame", zh: "每帧的像素颜色" },
      { en: "The camera trajectory", zh: "相机轨迹" },
      { en: "The training loss function", zh: "训练损失函数" },
      { en: "Precedence/dependency constraints on valid action sequences", zh: "有效动作序列上的先后/依赖约束" },
    ],
    correct: 3,
    explain: { en: "Like a grammar for language, it captures which steps can/must precede which — a learned prior that constrains plausible futures.", zh: "如同语言的语法，它刻画哪些步骤能/须先于哪些——约束可能未来的学到先验。" },
  },
  C9: {
    id: "C9-mcq",
    prompt: { en: "An ablation study works by…", zh: "消融研究的做法是……" },
    options: [
      { en: "Removing one component to measure its contribution", zh: "移除一个组件以衡量其贡献" },
      { en: "Adding more training data", zh: "增加更多训练数据" },
      { en: "Training for more epochs", zh: "训练更多轮次" },
      { en: "Using a larger model", zh: "使用更大的模型" },
    ],
    correct: 0,
    explain: { en: "Turning off one piece at a time isolates what each contributes — the standard way to understand why a system works.", zh: "一次关闭一个部件，分离各自的贡献——理解系统为何有效的标准方法。" },
  },

  // ── Track D ────────────────────────────────────────────────────────────────
  D1: {
    id: "D1-mcq",
    prompt: { en: "‘Drift’ in SLAM is…", zh: "SLAM 中的「漂移」是……" },
    options: [
      { en: "Unbounded accumulation of small incremental pose errors", zh: "逐帧位姿小误差的无界累积" },
      { en: "GPU overheating", zh: "GPU 过热" },
      { en: "Camera lens distortion", zh: "相机镜头畸变" },
      { en: "A sudden lighting change", zh: "突然的光照变化" },
    ],
    correct: 0,
    explain: { en: "Frame-to-frame pose errors compound without global correction; loop closure adds a constraint that redistributes and cancels the drift.", zh: "逐帧位姿误差在无全局校正下复合；回环加入约束重新分配并抵消漂移。" },
  },
  D2: {
    id: "D2-mcq",
    prompt: { en: "Visual odometry estimates camera motion by…", zh: "视觉里程计估计相机运动的方式是……" },
    options: [
      { en: "One global optimization over all frames at once", zh: "对所有帧一次性做全局优化" },
      { en: "Recognizing a revisited place", zh: "识别重访的地点" },
      { en: "Tracking features frame-to-frame (PnP)", zh: "逐帧跟踪特征（PnP）" },
      { en: "Labeling objects semantically", zh: "对物体做语义标注" },
    ],
    correct: 2,
    explain: { en: "The front-end (visual odometry) tracks features and solves an incremental pose per frame; the global back-end and loop closure tame the drift.", zh: "前端（视觉里程计）跟踪特征并逐帧求增量位姿；全局后端与回环驯服漂移。" },
  },
  D3: {
    id: "D3-mcq",
    prompt: { en: "A TSDF stores, per voxel,…", zh: "TSDF 为每个体素存储……" },
    options: [
      { en: "A truncated signed distance to the nearest surface", zh: "到最近曲面的截断符号距离" },
      { en: "The RGB color only", zh: "仅 RGB 颜色" },
      { en: "A semantic class id", zh: "一个语义类别 id" },
      { en: "A camera id", zh: "一个相机 id" },
    ],
    correct: 0,
    explain: { en: "TSDF = a signed distance clamped to a thin band near the surface; fusing many depth frames and extracting the zero-crossing yields a clean mesh.", zh: "TSDF = 在表面附近薄带内钳制的符号距离；融合多帧深度并提取零交叉得到干净网格。" },
  },
  D4: {
    id: "D4-mcq",
    prompt: { en: "Updating each map element's class probabilities across frames is called…", zh: "跨帧更新每个地图元素的类别概率，称为……" },
    options: [
      { en: "Marching cubes", zh: "Marching cubes" },
      { en: "Bayesian label fusion", zh: "贝叶斯标签融合" },
      { en: "Bundle adjustment", zh: "光束法平差" },
      { en: "Tube masking", zh: "管状掩码" },
    ],
    correct: 1,
    explain: { en: "Each view updates a per-element class distribution; pooling many views averages out flickering 2D errors — multi-frame denoising on semantics.", zh: "每个视角更新逐元素的类别分布；汇聚多视角平均掉闪烁的 2D 错误——语义上的多帧去噪。" },
  },
  D5: {
    id: "D5-mcq",
    prompt: { en: "In a 3D scene graph, nodes are ___ and edges are ___.", zh: "在 3D 场景图中，节点是___，边是___。" },
    options: [
      { en: "Objects / spatial relations", zh: "物体 / 空间关系" },
      { en: "Pixels / colors", zh: "像素 / 颜色" },
      { en: "Frames / timestamps", zh: "帧 / 时间戳" },
      { en: "Rays / depths", zh: "射线 / 深度" },
    ],
    correct: 0,
    explain: { en: "Nodes are objects (and places); edges are relations like ‘on’ or ‘next to’ — a compact symbolic scene model an LLM can reason over.", zh: "节点是物体（与地点）；边是「在…上」「在…旁」等关系——一个 LLM 可推理的紧凑符号场景模型。" },
  },
  D6: {
    id: "D6-mcq",
    prompt: { en: "Which representation tiles space itself rather than organizing around objects?", zh: "哪种表示平铺空间本身，而非围绕物体组织？" },
    options: [
      { en: "A scene graph", zh: "场景图" },
      { en: "An object database", zh: "物体数据库" },
      { en: "A verb/noun label set", zh: "动词/名词标签集" },
      { en: "Space-centric (voxels / TSDF / occupancy)", zh: "空间中心（体素/TSDF/占据）" },
    ],
    correct: 3,
    explain: { en: "Space-centric maps fill space (great for navigation/collision); object-centric maps organize around things (great for relations/language).", zh: "空间中心地图填充空间（擅长导航/碰撞）；物体中心地图围绕事物组织（擅长关系/语言）。" },
  },
  D7: {
    id: "D7-mcq",
    prompt: { en: "An ‘egocentric’ reference frame describes positions relative to…", zh: "「自我中心」参照系相对于___描述位置。" },
    options: [
      { en: "The observer / agent", zh: "观察者/智能体" },
      { en: "The world's fixed cardinal directions", zh: "世界固定的方位" },
      { en: "Another object's own intrinsic axes", zh: "另一物体自身的内在轴" },
      { en: "The camera's focal length", zh: "相机的焦距" },
    ],
    correct: 0,
    explain: { en: "Egocentric = relative to the observer (‘my left’); allocentric = relative to the world or another object. Robust reasoning must commit to a frame.", zh: "自我中心=相对观察者（「我的左边」）；他者中心=相对世界或另一物体。稳健推理须确定一个参照系。" },
  },
  D8: {
    id: "D8-mcq",
    prompt: { en: "Given the current state and a candidate action, a world model predicts…", zh: "给定当前状态与一个候选动作，世界模型预测……" },
    options: [
      { en: "The camera's focal length", zh: "相机的焦距" },
      { en: "A semantic class label", zh: "一个语义类别标签" },
      { en: "The resulting next state", zh: "由此产生的下一状态" },
      { en: "The training loss", zh: "训练损失" },
    ],
    correct: 2,
    explain: { en: "A world model is a learned transition function — state + action → next state. Chaining it rolls the future forward in imagination, enabling planning.", zh: "世界模型是学到的转移函数——状态 + 动作 → 下一状态。串联它在想象中把未来向前滚动，从而支持规划。" },
  },
  D9: {
    id: "D9-mcq",
    prompt: { en: "The capstone deliverable, ‘world memory’, is…", zh: "终极项目的交付物「世界记忆」是……" },
    options: [
      { en: "A single rendered image", zh: "一张渲染的图像" },
      { en: "A persistent, queryable semantic-geometric record of a scene", zh: "对场景的持久、可查询的语义-几何记录" },
      { en: "A list of hyperparameters", zh: "一份超参数列表" },
      { en: "A training loss curve", zh: "一条训练损失曲线" },
    ],
    correct: 1,
    explain: { en: "The pipeline turns raw frames into a persistent map / scene-graph you can query — pixels turned into world memory.", zh: "流水线把原始帧变成可查询的持久地图/场景图——把像素变成世界记忆。" },
  },
};
