import type { McqItem } from "../types";

// One auto-gradable multiple-choice question per lesson — a fast retrieval check
// that complements the open-ended "Check yourself" cards and feeds objective
// scoring in the per-track quiz. `correct` indexes into `options`.
export const lessonQuiz: Record<string, McqItem> = {
  // ── Track A ────────────────────────────────────────────────────────────────
  A1: {
    id: "A1-mcq",
    prompt: { en: "Why regress SMPL's ~80 parameters instead of ~6890 mesh vertices directly?", zh: "为什么回归 SMPL 的约 80 个参数，而非直接回归约 6890 个网格顶点？" },
    options: [
      { en: "The low-D parameter space is differentiable and every point is a valid human body", zh: "低维参数空间可微，且每一点都是有效人体" },
      { en: "80 numbers store more geometric detail than 6890 vertices", zh: "80 个数比 6890 个顶点存储更多几何细节" },
      { en: "Vertices cannot be rendered on a GPU", zh: "顶点无法在 GPU 上渲染" },
      { en: "It removes the need for any training data", zh: "它免除了对任何训练数据的需求" },
    ],
    correct: 0,
    explain: { en: "The parameters form a compact, differentiable space whose every point is anatomically valid — a strong prior that shrinks the output and regularizes the estimate.", zh: "参数构成一个紧凑、可微的空间，其中每一点都解剖学有效——一个缩小输出并正则化估计的强先验。" },
  },
  A2: {
    id: "A2-mcq",
    prompt: { en: "Why are heatmaps usually preferred over directly regressing (x, y) keypoint coordinates?", zh: "为什么热图通常优于直接回归 (x, y) 关键点坐标？" },
    options: [
      { en: "They preserve spatial structure and can express uncertainty / multi-modality", zh: "它们保留空间结构，并能表达不确定性/多模态" },
      { en: "They use less memory than two floats", zh: "它们比两个浮点数更省内存" },
      { en: "They make the network shallower", zh: "它们让网络更浅" },
      { en: "They remove the need for a backbone", zh: "它们免除了对骨干网络的需求" },
    ],
    correct: 0,
    explain: { en: "A heatmap is a dense spatial probability map: it trains stably, localizes well, and represents uncertainty that a single coordinate can't.", zh: "热图是稠密的空间概率图：训练稳定、定位良好，并表示单个坐标无法表达的不确定性。" },
  },
  A3: {
    id: "A3-mcq",
    prompt: { en: "Why might a skeleton-graph representation beat a flat vector of joint coordinates?", zh: "为什么骨架图表示可能优于关节坐标的扁平向量？" },
    options: [
      { en: "It encodes the body's known connectivity as an inductive bias", zh: "它把身体已知的连通性编码为归纳偏置" },
      { en: "Graphs always have fewer parameters", zh: "图总是参数更少" },
      { en: "It removes the need for temporal modeling", zh: "它免除了时序建模的需求" },
      { en: "Flat vectors can't be fed to neural nets", zh: "扁平向量无法喂给神经网络" },
    ],
    correct: 0,
    explain: { en: "A graph shares weights along anatomically meaningful edges and propagates information between connected joints; a flat vector discards this topology.", zh: "图沿解剖学上有意义的边共享权重，并在相连关节间传播信息；扁平向量丢弃了这一拓扑。" },
  },
  A4: {
    id: "A4-mcq",
    prompt: { en: "How can a reprojection loss train 3D mesh recovery without 3D ground truth?", zh: "重投影损失如何在没有 3D 真值的情况下训练 3D 网格恢复？" },
    options: [
      { en: "Project predicted 3D joints to 2D and match abundant 2D keypoint labels", zh: "把预测的 3D 关节投影到 2D，匹配大量 2D 关键点标注" },
      { en: "Compare predicted vertices to scanned ground-truth meshes", zh: "把预测顶点与扫描的真值网格比较" },
      { en: "Use a depth sensor for every training image", zh: "为每张训练图像使用深度传感器" },
      { en: "It can't — 3D labels are always required", zh: "做不到——总是需要 3D 标注" },
    ],
    correct: 0,
    explain: { en: "The network must output a 3D body that, viewed through the camera, explains the 2D evidence — so abundant 2D supervision constrains the 3D output.", zh: "网络必须输出这样一具 3D 身体：经相机观察时能解释 2D 证据——于是充足的 2D 监督约束了 3D 输出。" },
  },
  A5: {
    id: "A5-mcq",
    prompt: { en: "Why give hands and faces dedicated models (MANO/FLAME) instead of denser SMPL vertices?", zh: "为什么给手和脸专用模型（MANO/FLAME），而非更密的 SMPL 顶点？" },
    options: [
      { en: "They allocate parameters where articulation / expression actually varies", zh: "它们把参数分配到关节运动/表情真正变化之处" },
      { en: "SMPL cannot represent any small parts", zh: "SMPL 无法表示任何小部位" },
      { en: "Dedicated models need no training", zh: "专用模型无需训练" },
      { en: "Hands have fewer degrees of freedom than the torso", zh: "手的自由度比躯干少" },
    ],
    correct: 0,
    explain: { en: "Hands and faces have far higher articulation per unit area; dedicated bases put capacity where the relevant variation lives.", zh: "手和脸单位面积的关节自由度高得多；专用基把容量放在相关变化所在之处。" },
  },
  A6: {
    id: "A6-mcq",
    prompt: { en: "Why do networks struggle to regress rotations as quaternions or Euler angles?", zh: "为什么网络难以以四元数或欧拉角回归旋转？" },
    options: [
      { en: "These ≤4D encodings are discontinuous on the rotation manifold", zh: "这些 ≤4D 编码在旋转流形上不连续" },
      { en: "They use too much memory", zh: "它们占用太多内存" },
      { en: "They can only represent 2D rotations", zh: "它们只能表示 2D 旋转" },
      { en: "They are inherently non-differentiable", zh: "它们本质上不可微" },
    ],
    correct: 0,
    explain: { en: "Small rotation changes can require large jumps or sign flips; a smooth network can't fit that discontinuity. A continuous 6D encoding removes it.", zh: "旋转的微小变化可能要求大跳变或符号翻转；平滑网络无法拟合该不连续。连续的 6D 编码消除了它。" },
  },
  A7: {
    id: "A7-mcq",
    prompt: { en: "Why is physical plausibility (no foot-skating) hard for pure data-driven motion generators?", zh: "为什么纯数据驱动的运动生成器难以保证物理合理性（无脚滑）？" },
    options: [
      { en: "Plausibility is a global physical property the per-frame likelihood doesn't capture", zh: "合理性是逐帧似然不捕捉的全局物理性质" },
      { en: "Generators can't produce smooth motion", zh: "生成器无法产出平滑运动" },
      { en: "Foot contact is impossible to detect", zh: "脚的接触无法检测" },
      { en: "Diffusion models ignore the prompt", zh: "扩散模型忽略提示" },
    ],
    correct: 0,
    explain: { en: "Generators match pose statistics but don't enforce contact dynamics; small per-frame errors integrate into visible skating, so you need explicit contact/physics terms.", zh: "生成器匹配姿态统计，却不强制接触动力学；逐帧小误差累积成可见脚滑，故需显式的接触/物理项。" },
  },
  A8: {
    id: "A8-mcq",
    prompt: { en: "Why is contact a nearly 'free' supervision signal for human–scene interaction?", zh: "为什么接触对人–场景交互是近乎「免费」的监督信号？" },
    options: [
      { en: "Physics (support, non-penetration) holds every frame without any labeling", zh: "物理（支撑、非穿插）对每帧成立而无需标注" },
      { en: "Datasets always annotate contact", zh: "数据集总会标注接触" },
      { en: "Contact requires no coordinate frame", zh: "接触不需要坐标系" },
      { en: "It replaces the need for a body model", zh: "它替代了对人体模型的需求" },
    ],
    correct: 0,
    explain: { en: "Bodies must be supported and can't interpenetrate objects; these laws give 3D constraints on unlabeled data for free.", zh: "身体必须被支撑且不能与物体互相穿插；这些规律在无标注数据上免费提供 3D 约束。" },
  },
  A9: {
    id: "A9-mcq",
    prompt: { en: "Your fitted SMPL looks right in the image but is flipped in depth. Which term is most likely too weak?", zh: "你拟合的 SMPL 在图像里看着对，但深度上翻转了。最可能太弱的是哪一项？" },
    options: [
      { en: "The pose / depth prior (or a temporal / contact term)", zh: "姿态/深度先验（或时间/接触项）" },
      { en: "The reprojection term", zh: "重投影项" },
      { en: "The image resolution", zh: "图像分辨率" },
      { en: "The learning rate alone", zh: "仅仅是学习率" },
    ],
    correct: 0,
    explain: { en: "Reprojection alone is depth-ambiguous; a front/back-flip fits the 2D equally well. Strengthen the prior or add temporal/contact terms.", zh: "仅重投影是深度歧义的；前后翻转能同样好地拟合 2D。加强先验或加入时间/接触项。" },
  },

  // ── Track B ────────────────────────────────────────────────────────────────
  B1: {
    id: "B1-mcq",
    prompt: { en: "Why can't you recover a 3D point from a single calibrated image?", zh: "为什么无法从单张已标定图像恢复一个 3D 点？" },
    options: [
      { en: "Projection maps a whole viewing ray to one pixel, so depth is lost", zh: "投影把一整条视线映到一个像素，故深度丢失" },
      { en: "The intrinsics are unknown", zh: "内参未知" },
      { en: "Images are just 2D arrays", zh: "图像只是 2D 数组" },
      { en: "The camera isn't calibrated", zh: "相机未标定" },
    ],
    correct: 0,
    explain: { en: "One image fixes the ray direction but not the distance along it; you need a second view, priors, or motion.", zh: "单张图像确定射线方向，但不确定沿射线的距离；你需要第二个视图、先验或运动。" },
  },
  B2: {
    id: "B2-mcq",
    prompt: { en: "How does the epipolar constraint help correspondence search?", zh: "对极约束如何帮助对应搜索？" },
    options: [
      { en: "It restricts the match to a 1D line instead of the whole 2D image", zh: "它把匹配限制在一条 1D 直线上，而非整张 2D 图像" },
      { en: "It removes the need for matching", zh: "它免除了匹配的需求" },
      { en: "It recovers depth without a second view", zh: "它无需第二视图即可恢复深度" },
      { en: "It calibrates the camera", zh: "它标定相机" },
    ],
    correct: 0,
    explain: { en: "A point's match must lie on a known epipolar line, cutting candidates and false matches dramatically.", zh: "某点的匹配必落在一条已知对极线上，大幅削减候选与错误匹配。" },
  },
  B3: {
    id: "B3-mcq",
    prompt: { en: "What does bundle adjustment minimize?", zh: "光束法平差最小化什么？" },
    options: [
      { en: "Total reprojection error over all camera poses and 3D points jointly", zh: "对所有相机位姿与 3D 点联合的总重投影误差" },
      { en: "Only the latest camera's pose", zh: "仅最新相机的位姿" },
      { en: "The photometric loss of a NeRF", zh: "NeRF 的光度损失" },
      { en: "The number of 3D points", zh: "3D 点的数量" },
    ],
    correct: 0,
    explain: { en: "BA jointly refines all poses (often intrinsics) and all points so the whole reconstruction is globally consistent.", zh: "BA 联合精修所有位姿（常含内参）与所有点，使整个重建全局一致。" },
  },
  B4: {
    id: "B4-mcq",
    prompt: { en: "In a signed-distance representation, where is the surface?", zh: "在符号距离表示中，表面在哪里？" },
    options: [
      { en: "The zero level-set, where f(x) = 0", zh: "零等值面，即 f(x) = 0 之处" },
      { en: "Wherever f(x) is largest", zh: "f(x) 最大之处" },
      { en: "At the grid corners", zh: "在网格角点" },
      { en: "Only at stored vertices", zh: "仅在存储的顶点处" },
    ],
    correct: 0,
    explain: { en: "An SDF returns signed distance to the nearest surface (negative inside); the surface is exactly f(x)=0, with normals ∇f.", zh: "SDF 返回到最近表面的有符号距离（内部为负）；表面正是 f(x)=0，法向为 ∇f。" },
  },
  B5: {
    id: "B5-mcq",
    prompt: { en: "What signal trains a NeRF, which has no 3D ground truth?", zh: "什么信号训练了没有 3D 真值的 NeRF？" },
    options: [
      { en: "Photometric loss: rendered pixels vs real pixels across posed images", zh: "光度损失：跨已知位姿图像的渲染像素与真实像素" },
      { en: "A 3D mesh supervision loss", zh: "3D 网格监督损失" },
      { en: "Depth-sensor readings only", zh: "仅深度传感器读数" },
      { en: "Hand-labeled densities", zh: "手工标注的密度" },
    ],
    correct: 0,
    explain: { en: "Differentiable volume rendering lets multi-view photometric consistency backprop into the MLP — no 3D labels needed.", zh: "可微体渲染让多视图光度一致性反向传播进 MLP——无需 3D 标注。" },
  },
  B6: {
    id: "B6-mcq",
    prompt: { en: "Why does Instant-NGP's hash grid train so much faster than plain NeRF?", zh: "为什么 Instant-NGP 的哈希网格比普通 NeRF 训练快得多？" },
    options: [
      { en: "Capacity lives in directly-indexed local features + a tiny MLP, so queries are cheap", zh: "容量驻留在可直接索引的局部特征 + 极小 MLP，故查询便宜" },
      { en: "It uses a much larger MLP", zh: "它用一个大得多的 MLP" },
      { en: "It skips volume rendering", zh: "它跳过体渲染" },
      { en: "It needs no training data", zh: "它无需训练数据" },
    ],
    correct: 0,
    explain: { en: "A monolithic MLP must encode the whole scene; a grid is read locally so each ray is cheap and convergence is fast.", zh: "单体 MLP 必须编码整个场景；网格在本地读取，故每条射线便宜、收敛快。" },
  },
  B7: {
    id: "B7-mcq",
    prompt: { en: "Why is 3D Gaussian Splatting real-time when NeRF usually isn't?", zh: "为什么 3D 高斯泼溅能实时，而 NeRF 通常不能？" },
    options: [
      { en: "It rasterizes a finite set of explicit Gaussians instead of integrating an MLP along each ray", zh: "它光栅化有限个显式高斯，而非沿每条射线积分 MLP" },
      { en: "It uses a deeper network", zh: "它用更深的网络" },
      { en: "It renders at lower resolution", zh: "它以更低分辨率渲染" },
      { en: "It precomputes every possible view", zh: "它预计算所有可能的视角" },
    ],
    correct: 0,
    explain: { en: "NeRF runs hundreds of MLP evals per pixel; 3DGS alpha-blends explicit Gaussians via the GPU pipeline — far less per-pixel compute.", zh: "NeRF 每像素数百次 MLP 求值；3DGS 经 GPU 管线 alpha 混合显式高斯——每像素计算量小得多。" },
  },
  B8: {
    id: "B8-mcq",
    prompt: { en: "Why factor a dynamic scene into a canonical model + deformation field?", zh: "为什么把动态场景分解为标准模型 + 形变场？" },
    options: [
      { en: "Appearance is shared across time; only motion varies, which is far more data-efficient", zh: "外观跨时间共享，只有运动在变，数据效率高得多" },
      { en: "It avoids needing any priors", zh: "它免除了对任何先验的需求" },
      { en: "It removes camera motion", zh: "它消除相机运动" },
      { en: "It reconstructs each frame independently", zh: "它独立重建每一帧" },
    ],
    correct: 0,
    explain: { en: "One canonical model concentrates data on a consistent reconstruction and isolates the time-varying part into the deformation field.", zh: "一个标准模型把数据集中到一致的重建上，并把随时间变化的部分隔离进形变场。" },
  },
  B9: {
    id: "B9-mcq",
    prompt: { en: "Your NeRF has floaters (semi-transparent blobs in empty space). Most likely cause?", zh: "你的 NeRF 出现漂浮物（空中的半透明团块）。最可能的成因？" },
    options: [
      { en: "Density is under-constrained where too few / poorly-distributed views observe that region", zh: "在观测过少/分布差的区域，密度欠约束" },
      { en: "The MLP is too deep", zh: "MLP 太深" },
      { en: "Positional encoding is enabled", zh: "启用了位置编码" },
      { en: "The learning rate is too low", zh: "学习率太低" },
    ],
    correct: 0,
    explain: { en: "Few rays see that region, so the optimizer parks spurious density there. Fix with more views or density regularization.", zh: "很少射线看到那个区域，优化器便在那里停放虚假密度。用更多视角或密度正则修复。" },
  },

  // ── Track C ────────────────────────────────────────────────────────────────
  C1: {
    id: "C1-mcq",
    prompt: { en: "In egocentric video, why is camera motion a signal rather than just noise?", zh: "在第一人称视频中，为什么相机运动是信号而非仅是噪声？" },
    options: [
      { en: "Head motion is a proxy for where the wearer is looking (their attention)", zh: "头部运动是佩戴者在看哪里（其注意力）的代理" },
      { en: "It removes the need for a backbone", zh: "它免除了对骨干网络的需求" },
      { en: "It stabilizes the background", zh: "它稳定了背景" },
      { en: "It encodes the camera's intrinsics", zh: "它编码了相机内参" },
    ],
    correct: 0,
    explain: { en: "The camera moves with the head, so its motion tracks the wearer's gaze/attention and encodes ego-motion — useful, not nuisance.", zh: "相机随头部移动，故其运动跟踪佩戴者的注视/注意力并编码自我运动——是有用信号，而非干扰。" },
  },
  C2: {
    id: "C2-mcq",
    prompt: { en: "Why is a participant/kitchen-held-out split more meaningful than a random frame split?", zh: "为什么按参与者/厨房留出的划分比随机帧划分更有意义？" },
    options: [
      { en: "It forces generalization to unseen scenes/hands instead of memorizing appearance", zh: "它迫使泛化到未见的场景/手，而非记住外观" },
      { en: "It gives more training data", zh: "它提供更多训练数据" },
      { en: "It is faster to compute", zh: "它计算更快" },
      { en: "It balances the verb/noun classes", zh: "它平衡了动词/名词类别" },
    ],
    correct: 0,
    explain: { en: "Random splits leak the same environment/objects into train and test, inflating scores; holding out whole participants/kitchens tests real generalization.", zh: "随机划分把相同环境/物体泄漏到训练与测试，虚高分数；留出整个参与者/厨房才考验真正的泛化。" },
  },
  C3: {
    id: "C3-mcq",
    prompt: { en: "Why does VideoMAE mask ~90% of patches while image MAE masks ~75%?", zh: "为什么 VideoMAE 掩盖约 90% 的块，而图像 MAE 约 75%？" },
    options: [
      { en: "Video is temporally redundant; only aggressive masking stops copying from adjacent frames", zh: "视频在时间上冗余；只有激进掩码才能阻止从相邻帧复制" },
      { en: "Video has more colors", zh: "视频颜色更多" },
      { en: "It makes the model smaller", zh: "它让模型更小" },
      { en: "GPUs require 90%", zh: "GPU 要求 90%" },
    ],
    correct: 0,
    explain: { en: "With moderate masking the model just copies a neighboring frame; ~90% + tube masking forces genuine spatio-temporal understanding.", zh: "中等掩码下模型只会复制相邻帧；约 90% + 管状掩码逼出真正的时空理解。" },
  },
  C4: {
    id: "C4-mcq",
    prompt: { en: "Why is top-1 accuracy a poor metric for action anticipation?", zh: "为什么 top-1 准确率不适合作为动作预判的指标？" },
    options: [
      { en: "The future is multi-modal — several next actions are plausible; top-k rewards covering them", zh: "未来是多模态的——几个下一动作都合理；top-k 奖励覆盖它们" },
      { en: "Top-1 is too easy", zh: "Top-1 太容易" },
      { en: "Anticipation has no labels", zh: "预判没有标签" },
      { en: "It ignores the verb", zh: "它忽略动词" },
    ],
    correct: 0,
    explain: { en: "After 'take pan', both 'add oil' and 'add egg' are reasonable. Top-1 punishes a well-calibrated model; top-k matches the real goal.", zh: "「拿锅」之后，「加油」和「加蛋」都合理。Top-1 惩罚校准良好的模型；top-k 契合真实目标。" },
  },
  C5: {
    id: "C5-mcq",
    prompt: { en: "Which first-person prior most helps detect the wearer's own hands?", zh: "哪个第一人称先验最有助于检测佩戴者自己的手？" },
    options: [
      { en: "They enter from the bottom edge, forearm leading inward, at consistent scale/orientation", zh: "它们从底边进入，前臂朝内引导，尺度/朝向一致" },
      { en: "They are always in sharp focus", zh: "它们总是清晰对焦" },
      { en: "They are the brightest pixels", zh: "它们是最亮的像素" },
      { en: "They never overlap objects", zh: "它们从不与物体重叠" },
    ],
    correct: 0,
    explain: { en: "Own hands appear from a consistent direction — a strong positional/orientation prior for own-vs-other and edge truncation.", zh: "自己的手以一致方向出现——是区分自己/他人与处理边缘截断的强位置/朝向先验。" },
  },
  C6: {
    id: "C6-mcq",
    prompt: { en: "How does the 'active object' concept help action recognition?", zh: "「活动物体」概念如何帮助动作识别？" },
    options: [
      { en: "It collapses a cluttered scene to the one object being manipulated", zh: "它把杂乱场景收缩为正被操作的那一个物体" },
      { en: "It removes the need for hands", zh: "它免除了对手的需求" },
      { en: "It labels every object in view", zh: "它标注视野中的每个物体" },
      { en: "It tracks the background", zh: "它跟踪背景" },
    ],
    correct: 0,
    explain: { en: "Focusing on the manipulated object cuts background distractors and ties the (verb, noun) prediction to the relevant noun.", zh: "聚焦被操作物体削减背景干扰，并把（动词，名词）预测绑定到相关名词。" },
  },
  C7: {
    id: "C7-mcq",
    prompt: { en: "Why does gaze typically lead the corresponding hand action in time?", zh: "为什么注视在时间上通常领先于相应的手部动作？" },
    options: [
      { en: "Motor planning fixates the target to guide the reach, so the eye lands first", zh: "运动规划先注视目标以引导伸手，故眼睛先落到目标上" },
      { en: "Eyes move faster than the camera shutter", zh: "眼睛动得比相机快门快" },
      { en: "Gaze is recorded at a higher frame rate", zh: "注视以更高帧率记录" },
      { en: "Hands are slower to detect", zh: "手更难被检测" },
    ],
    correct: 0,
    explain: { en: "The visual system gathers spatial info before the reach commits, so gaze precedes the hand — making it a strong anticipation cue.", zh: "视觉系统在伸手「下注」前先收集空间信息，故注视先于手——使其成为强预判线索。" },
  },
  C8: {
    id: "C8-mcq",
    prompt: { en: "How does inferring the latent goal improve action anticipation?", zh: "推断潜在目标如何改进动作预判？" },
    options: [
      { en: "It collapses next-action probabilities onto a procedure's steps and valid orderings", zh: "它把下一动作的概率收缩到某流程的步骤及其有效顺序" },
      { en: "It removes the need for video", zh: "它免除了对视频的需求" },
      { en: "It increases the label space", zh: "它扩大标签空间" },
      { en: "It ignores temporal order", zh: "它忽略时间顺序" },
    ],
    correct: 0,
    explain: { en: "Knowing 'making coffee' turns open-ended forecasting into constrained sequence completion.", zh: "知道「冲咖啡」把开放式预测变成受约束的序列补全。" },
  },
  C9: {
    id: "C9-mcq",
    prompt: { en: "Why reproduce a simple baseline before the state of the art?", zh: "为什么先复现简单基线再做最先进方法？" },
    options: [
      { en: "It's fast to get correct, exposes the data/metric, and gives a trustworthy reference", zh: "它能快速做对、清晰暴露数据/指标，并提供可信参考" },
      { en: "SOTA has no code", zh: "SOTA 没有代码" },
      { en: "Baselines always beat SOTA", zh: "基线总能击败 SOTA" },
      { en: "It needs no evaluation", zh: "它无需评估" },
    ],
    correct: 0,
    explain: { en: "SOTA reproductions are brittle and obscure what matters; you can only attribute improvement against a baseline you fully understand.", zh: "SOTA 复现脆弱且掩盖关键；只有对着你完全理解的基线，才能把改进归因。" },
  },

  // ── Track D ────────────────────────────────────────────────────────────────
  D1: {
    id: "D1-mcq",
    prompt: { en: "Why does a SLAM front-end (visual odometry) alone inevitably drift?", zh: "为什么仅有 SLAM 前端（视觉里程计）必然漂移？" },
    options: [
      { en: "It composes incremental frame-to-frame estimates whose small errors accumulate unboundedly", zh: "它把逐帧增量估计累加，其小误差无界累积" },
      { en: "Cameras are never calibrated", zh: "相机从不标定" },
      { en: "It uses too few pixels", zh: "它用的像素太少" },
      { en: "It runs too fast", zh: "它运行太快" },
    ],
    correct: 0,
    explain: { en: "Without a global back-end and loop closures linking distant times, accumulated error makes the trajectory diverge.", zh: "没有全局后端与连接远隔时刻的回环，累积误差使轨迹偏离。" },
  },
  D2: {
    id: "D2-mcq",
    prompt: { en: "Which classical operation does per-frame camera tracking in SLAM correspond to?", zh: "SLAM 中逐帧的相机跟踪对应哪个经典操作？" },
    options: [
      { en: "PnP — pose from known 3D points and their 2D detections", zh: "PnP——从已知 3D 点及其 2D 检测求位姿" },
      { en: "Triangulation", zh: "三角测量" },
      { en: "Marching Cubes", zh: "Marching Cubes" },
      { en: "Positional encoding", zh: "位置编码" },
    ],
    correct: 0,
    explain: { en: "Tracking = PnP, new geometry = triangulation, consistency = bundle adjustment — Track B's kernel run online.", zh: "跟踪 = PnP，新几何 = 三角测量，一致性 = 光束法平差——Track B 的内核在线运行。" },
  },
  D3: {
    id: "D3-mcq",
    prompt: { en: "How does TSDF fusion produce a clean surface from noisy depth?", zh: "TSDF 融合如何从含噪深度产出干净表面？" },
    options: [
      { en: "Weighted-averaging signed distances across many frames cancels independent per-frame noise", zh: "跨多帧对符号距离加权平均，抵消逐帧的独立噪声" },
      { en: "It picks the single best depth frame", zh: "它挑选单个最佳深度帧" },
      { en: "It ignores all but the nearest voxel", zh: "它只保留最近的体素" },
      { en: "It uses a deeper MLP", zh: "它用更深的 MLP" },
    ],
    correct: 0,
    explain: { en: "Multi-frame fusion: redundancy across observations denoises while the true surface reinforces; the zero level-set is the surface.", zh: "多帧融合：观测间的冗余去噪，而真实表面被强化；零等值面即表面。" },
  },
  D4: {
    id: "D4-mcq",
    prompt: { en: "Why store a class probability distribution per map element instead of a single label?", zh: "为什么为每个地图元素存类别概率分布，而非单一标签？" },
    options: [
      { en: "It supports multi-frame Bayesian fusion and keeps uncertainty until evidence resolves it", zh: "它支持多帧贝叶斯融合，并把不确定性保留到证据消解" },
      { en: "It uses less memory", zh: "它更省内存" },
      { en: "Single labels can't be rendered", zh: "单一标签无法渲染" },
      { en: "Distributions need no training", zh: "分布无需训练" },
    ],
    correct: 0,
    explain: { en: "A single label locks in early mistakes; a distribution lets each view update the belief and combine conflicting observations robustly.", zh: "单一标签锁死早期错误；分布让每个视角更新信念并稳健地合并冲突观测。" },
  },
  D5: {
    id: "D5-mcq",
    prompt: { en: "What can a 3D scene graph express that a flat semantic map cannot?", zh: "3D 场景图能表达而扁平语义地图不能的是什么？" },
    options: [
      { en: "Relations between objects ('on', 'next to') and hierarchy (object→room→floor)", zh: "物体间的关系（「在…上」「在…旁」）与层级（物体→房间→楼层）" },
      { en: "The color of each voxel", zh: "每个体素的颜色" },
      { en: "Camera intrinsics", zh: "相机内参" },
      { en: "Depth at every pixel", zh: "每个像素的深度" },
    ],
    correct: 0,
    explain: { en: "A flat map only says which labels exist where; the graph encodes the relational/structural organization reasoning and planning need.", zh: "扁平地图只说哪些标签在哪；图编码了推理与规划所需的关系/结构组织。" },
  },
  D6: {
    id: "D6-mcq",
    prompt: { en: "A robot must navigate around furniture without hitting it. Best representation?", zh: "机器人须绕过家具而不撞到。最佳表示？" },
    options: [
      { en: "Space-centric (occupancy / TSDF) — metric free vs occupied space everywhere", zh: "空间中心（占据/TSDF）——处处的度量自由/被占据空间" },
      { en: "An object-only scene graph", zh: "仅物体的场景图" },
      { en: "A list of CLIP features", zh: "一组 CLIP 特征" },
      { en: "A 2D verb/noun label set", zh: "一个 2D 动词/名词标签集" },
    ],
    correct: 0,
    explain: { en: "Collision-free navigation needs metric free-space; an object graph abstracts that away and can't guarantee clearance.", zh: "无碰撞导航需要度量自由空间；物体图抽象掉了它，无法保证间隙。" },
  },
  D7: {
    id: "D7-mcq",
    prompt: { en: "'Representation determines reasoning' means…", zh: "「表示决定推理」意味着……" },
    options: [
      { en: "What you can infer is bounded by how the scene is represented", zh: "你能推断什么，受限于场景如何被表示" },
      { en: "Bigger models always reason better", zh: "更大的模型总是推理更好" },
      { en: "All representations answer all questions", zh: "所有表示都能回答所有问题" },
      { en: "Reasoning needs no representation", zh: "推理不需要表示" },
    ],
    correct: 0,
    explain: { en: "'Can I walk there?' needs a metric map; 'is the book on the shelf?' needs a relational graph — neither answers the other well.", zh: "「我能走到那吗？」需要度量地图；「书在架子上吗？」需要关系图——任一都答不好另一个。" },
  },
  D8: {
    id: "D8-mcq",
    prompt: { en: "What does a world model add over a (semantic) map?", zh: "世界模型相比（语义）地图增加了什么？" },
    options: [
      { en: "Dynamics — it predicts how state changes under actions, enabling planning by simulation", zh: "动力学——它预测状态在动作下如何变化，从而支持以模拟来规划" },
      { en: "Higher-resolution geometry", zh: "更高分辨率的几何" },
      { en: "Faster rendering", zh: "更快的渲染" },
      { en: "More semantic labels", zh: "更多语义标签" },
    ],
    correct: 0,
    explain: { en: "A map is static memory; a world model lets the agent imagine rollouts, evaluate outcomes, and plan before acting.", zh: "地图是静态记忆；世界模型让智能体想象滚动、评估结果，并在行动前规划。" },
  },
  D9: {
    id: "D9-mcq",
    prompt: { en: "Which is a genuine cross-track connection in this curriculum?", zh: "以下哪个是本课程中真正的跨赛道连接？" },
    options: [
      { en: "Track B's bundle adjustment is Track D's SLAM back-end", zh: "Track B 的光束法平差就是 Track D 的 SLAM 后端" },
      { en: "Heatmaps are the same as loop closure", zh: "热图与回环检测相同" },
      { en: "SMPL is identical to a hash grid", zh: "SMPL 与哈希网格相同" },
      { en: "Gaze prediction replaces triangulation", zh: "注视预测取代三角测量" },
    ],
    correct: 0,
    explain: { en: "The geometric kernel (BA), the SDF (B↔D's TSDF), and multi-frame fusion all recur across tracks — one system, not four.", zh: "几何内核（BA）、SDF（B↔D 的 TSDF）与多帧融合都跨赛道复现——是一个系统，而非四个。" },
  },
};
