import type { Bilingual } from "../types";

// One concrete "common pitfall / misconception" per lesson — the mistake a newcomer
// (or a rushing practitioner) actually makes. Shown as a "Watch out" callout.
export const lessonPitfalls: Record<string, Bilingual> = {
  // Track A
  A1: { en: "Regressing the ~6890 vertices directly (instead of the ~80 parameters) — outputs stop looking human. And θ are relative joint *rotations*, not 3D joint positions.", zh: "直接回归约 6890 个顶点（而非约 80 个参数）——输出会不像人。且 θ 是相对关节*旋转*，不是 3D 关节位置。" },
  A2: { en: "Taking a hard argmax of the heatmap and back-propagating through it — it's not differentiable; use soft-argmax. Lifting 2D→3D without temporal/body priors stays depth-ambiguous (front/back flips).", zh: "对热图取硬 argmax 再反向传播——它不可微，要用 soft-argmax。不带时序/身体先验地把 2D 抬到 3D，仍有深度歧义（前后翻转）。" },
  A3: { en: "Feeding absolute joint positions makes the model location-dependent — the same action elsewhere fails. Prefer velocities or a root-relative, normalized frame.", zh: "喂入绝对关节位置会让模型依赖位置——同一动作换个地方就失效。应使用速度或相对根节点的归一化坐标。" },
  A4: { en: "Optimizing reprojection alone yields a depth-flipped body that still fits the 2D — always add a pose prior. Weak-perspective ≠ full perspective; mismatches cause systematic scale/offset errors.", zh: "只优化重投影会得到仍能拟合 2D 的深度翻转身体——务必加姿态先验。弱透视≠完整透视；不匹配会造成系统性的尺度/偏移误差。" },
  A5: { en: "A 2D hand box can't tell contact — you need the 3D mesh. And don't fit hands at body resolution: under-parameterized hands miss grasp detail (that's why MANO exists).", zh: "2D 手框判断不了接触——需要 3D 网格。且别用身体的分辨率拟合手：欠参数化会丢失抓取细节（这正是 MANO 存在的原因）。" },
  A6: { en: "Regressing Euler angles or quaternions and blaming the optimizer for instability near 180°/sign flips — that's the discontinuity. Use 6D, and remember to re-orthonormalize a predicted matrix.", zh: "回归欧拉角或四元数，却把 180°/符号翻转附近的不稳定归咎于优化器——那就是不连续。用 6D，并记得把预测矩阵重新正交化。" },
  A7: { en: "Per-frame plausibility ≠ global plausibility: a generator can match pose statistics yet still foot-skate. Add contact/physics terms. And diffusion needs many denoising steps — one step is still noise.", zh: "逐帧合理≠整体合理：生成器能匹配姿态统计，却仍会脚滑。要加接触/物理项。且扩散需要多步去噪——单步仍是噪声。" },
  A8: { en: "Ignoring the scene leaves depth ambiguous — but also: contact constraints need the body and scene in the SAME coordinate frame. Mixing frames silently breaks everything.", zh: "忽略场景会留下深度歧义——但还要注意：接触约束需要身体与场景在同一坐标系。混用坐标系会悄悄毁掉一切。" },
  A9: { en: "If the fit looks right in the image but flipped in depth, your prior/temporal term is too weak — not your reprojection. Diagnose term-by-term instead of just lowering the total loss.", zh: "若拟合在图像里对、深度上翻转，是你的先验/时间项太弱——而非重投影。要逐项诊断，而不是只降低总损失。" },
  // Track B
  B1: { en: "Expecting depth from a single calibrated image — impossible; a pixel is a whole ray. And skipping the perspective divide (treating homogeneous coords as Euclidean) gives wrong projections.", zh: "指望从单张已标定图像得到深度——不可能，一个像素是一整条射线。且跳过透视除法（把齐次坐标当欧氏坐标）会得到错误投影。" },
  B2: { en: "A tiny baseline (cameras nearly coincident) makes triangulated depth wildly noise-sensitive. And matching points across views — not the triangulation math — is the real bottleneck.", zh: "极小的基线（两相机几乎重合）会让三角测量的深度对噪声极度敏感。且跨视图匹配点——而非三角测量本身——才是真正的瓶颈。" },
  B3: { en: "Bundle adjustment is non-convex: a poor initialization settles into a bad minimum. And ignoring the problem's sparsity (Schur complement) makes large scenes intractable.", zh: "光束法平差是非凸的：差的初始化会陷入糟糕的极小。且忽视问题的稀疏性（Schur 补）会让大场景变得不可行。" },
  B4: { en: "Treating an MLP's output as a true distance — without an eikonal constraint it's only an approximate SDF, so normals drift. Extracting the surface on a too-coarse grid misses thin features.", zh: "把 MLP 输出当作真实距离——没有 eikonal 约束它只是近似 SDF，法向会漂移。在过粗网格上提取表面会漏掉薄结构。" },
  B5: { en: "Without positional encoding NeRF is blurry (low-frequency bias) — people blame capacity when it's the input encoding. And NeRF assumes accurate poses; bad poses masquerade as model failure.", zh: "没有位置编码 NeRF 会很糊（低频偏置）——人们常归咎于容量，其实是输入编码。且 NeRF 假设位姿准确；坏位姿会伪装成模型失败。" },
  B6: { en: "Obsessing over hash collisions — the tiny MLP and multi-resolution levels resolve them. The real failure mode is a table too small to hold the scene's detail.", zh: "纠结哈希冲突——小 MLP 与多分辨率层级能解决它们。真正的失败是表太小，装不下场景细节。" },
  B7: { en: "Too few or badly-initialized Gaussians give blurry, holey renders — adaptive densification matters. And without enough viewpoint coverage, Gaussians overfit into floaters.", zh: "高斯太少或初始化不当会得到模糊、破洞的渲染——自适应稠密化很重要。且视角覆盖不足时，高斯会过拟合成漂浮物。" },
  B8: { en: "Reconstructing each frame independently wastes data and flickers — share a canonical model. Without rigidity priors the deformation field explains pixels with impossible, jelly-like motion.", zh: "逐帧独立重建浪费数据且会闪烁——应共享标准模型。没有刚性先验，形变场会用不可能的「果冻」运动去解释像素。" },
  B9: { en: "Floaters are usually too few / poorly-distributed views — not the model. Blur or ghosting? Check (and re-run COLMAP for) the camera poses before blaming the renderer.", zh: "漂浮物通常是视角太少/分布差——而非模型。模糊或重影？在归咎渲染器前，先检查相机位姿（必要时重跑 COLMAP）。" },
  // Track C
  C1: { en: "Applying third-person action models directly — they assume a visible full body and a static background, both absent here. And treating camera motion as noise to subtract discards a cue to where the wearer is looking.", zh: "直接套用第三人称动作模型——它们假设可见全身与静态背景，这里两者皆无。且把相机运动当噪声扣除，会丢掉「佩戴者在看哪里」这条线索。" },
  C2: { en: "Random train/test splits leak the same kitchen and object instances into both → inflated scores. Split by participant/environment. And don't let overall accuracy hide rare-class (long-tail) failure.", zh: "随机划分会把相同厨房与物体实例泄漏到两侧 → 虚高分数。要按参与者/环境划分。且别让总准确率掩盖稀有类（长尾）的失败。" },
  C3: { en: "Image-level masking (~75%) is too easy on video — the model just copies adjacent frames. Video needs ~90% tube masking. And SlowFast's two pathways must be *fused*, not run separately.", zh: "图像级掩码（约 75%）在视频上太容易——模型只会复制相邻帧。视频需要约 90% 的管状掩码。且 SlowFast 的双通路必须*融合*，而非各自独立运行。" },
  C4: { en: "Scoring anticipation with top-1 punishes well-calibrated models — the future is multi-modal; use top-k. And anticipation must use only the PAST; accidentally peeking at future frames is a classic leak.", zh: "用 top-1 评估预判会惩罚校准良好的模型——未来是多模态的，用 top-k。且预判只能用过去；不小心看了未来帧是经典的泄漏。" },
  C5: { en: "Treating all hands alike — you must tell own vs other and left vs right, or interaction reasoning breaks. And a box covers hand + object together; use a pixel mask for contact.", zh: "把所有手一视同仁——必须区分自己/他人、左/右，否则交互推理会崩。且一个框会同时盖住手和物体；接触要用像素掩码。" },
  C6: { en: "Detecting hand and object independently can output physically impossible pairs (a power grasp on a needle) — infer them jointly. And without picking the active object, the signal drowns in clutter.", zh: "独立检测手与物体会输出物理上不可能的组合（对一根针用力握）——应联合推断。且不选出活动物体，信号会淹没在杂乱中。" },
  C7: { en: "Assuming gaze sits exactly on the action — gaze LEADS the hands by a fraction of a second; that lead time IS the predictive signal. And don't assume an eye-tracker; predict saliency when it's absent.", zh: "以为注视正好落在动作上——注视比手领先零点几秒；这段领先时间正是预测信号。且别假设有眼动仪；没有时要预测显著性。" },
  C8: { en: "Modeling a task as a fixed sequence breaks on valid reorderings (sugar before or after milk) — use a partial order. And forecasting next actions without inferring the goal leaves the future under-constrained.", zh: "把任务建成固定序列，会在合法的重排（先加糖或先加奶）上出错——用偏序。且不推断目标就预测下一动作，会让未来欠约束。" },
  C9: { en: "Chasing SOTA before a trustworthy baseline — you can't attribute your gains. Report on the held-out split, and run a shuffle-control: if accuracy doesn't drop to chance, your number is leakage.", zh: "在有可信基线前追 SOTA——无法把提升归因于自己。要在留出划分上报告，并跑打乱对照：若准确率不跌到随机，你的数字就是泄漏。" },
  // Track D
  D1: { en: "Expecting visual odometry alone to stay accurate — it drifts without bound; loop closure + global optimization aren't optional. And a *wrong* loop closure is worse than none — it corrupts the whole map.", zh: "指望仅靠视觉里程计保持准确——它会无界漂移；回环 + 全局优化不是可选项。且*错误*的回环比没有更糟——会污染整张地图。" },
  D2: { en: "Treating SLAM as a separate field from SfM — it's the same geometry, online. Reinventing PnP/triangulation/BA instead of reusing Track B wastes effort; the only real difference is the time budget.", zh: "把 SLAM 当作与 SfM 不同的领域——它就是在线的同一套几何。重新发明 PnP/三角测量/BA 而不复用 Track B 是浪费；唯一真正的区别是时间预算。" },
  D3: { en: "Not truncating the SDF wastes huge memory and blurs the surface. And fusing without per-voxel weights lets a single bad depth frame wreck the average — weight by confidence.", zh: "不截断 SDF 会浪费巨量内存并模糊表面。且不带逐体素权重地融合，会让一帧坏深度毁掉平均——要按置信度加权。" },
  D4: { en: "Storing one hard label per voxel locks in early mistakes — store a distribution and Bayes-fuse across frames. And a fixed label set can't answer open-vocabulary queries; that's what CLIP features are for.", zh: "每个体素只存单一硬标签会锁死早期错误——应存分布并跨帧贝叶斯融合。且固定标签集回答不了开放词汇查询；这正是 CLIP 特征的用途。" },
  D5: { en: "A flat list of objects is not a scene graph — without explicit relations and hierarchy you can't answer 'is the mug on the table?'. And hand the compact graph to an LLM, not a raw point cloud.", zh: "一张物体清单不是场景图——没有显式关系与层级，回答不了「杯子在桌上吗？」。且要把紧凑的图交给 LLM，而非原始点云。" },
  D6: { en: "Forcing one representation to do everything — an object graph can't guarantee collision clearance, and an occupancy grid can't reason about relations. Choose per task, or keep both layers linked.", zh: "强迫一种表示包办一切——物体图保证不了避障间隙，占据栅格推理不了关系。按任务选，或让两层互相链接。" },
  D7: { en: "Answering 'left of the chair' without committing to a reference frame — the answer flips with viewpoint. And remember: what you CAN ask is bounded by how you stored the scene.", zh: "不确定参照系就回答「椅子左边」——答案随视角翻转。且记住：你「能问什么」受限于你如何存储场景。" },
  D8: { en: "Confusing a map with a world model — a map remembers the past, a world model predicts the future. Without learned dynamics you can't plan by imagining, and you're back to real-world trial-and-error.", zh: "把地图和世界模型混淆——地图记忆过去，世界模型预测未来。没有学到的动力学就无法以想象来规划，只能回到真实世界试错。" },
  D9: { en: "Building the full pipeline before any stage works — debug each stage on a short sequence with a trusted metric first. And lean on the cross-track reuse; don't re-implement BA / SDF / CLIP from scratch.", zh: "在任一阶段跑通前就搭整条流水线——先在短序列上用可信指标逐段调试。且善用跨赛道复用；别从零重写 BA / SDF / CLIP。" },
};
