// Extract each lesson snippet's executed output (printed stdout + the figure) from
// the pre-executed notebooks into web assets, so the lesson page can show the
// result inline (behind a "predict it, then reveal" toggle).
//   public/code-output/<ID>.png      the matplotlib figure
//   src/lib/curriculum/codeOutputs.ts  { stdout, image } per lesson
// Run AFTER notebooks are executed:  node scripts/gen-outputs.mjs
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const nbDir = path.join(root, "notebooks");
const imgDir = path.join(root, "public/code-output");
fs.mkdirSync(imgDir, { recursive: true });

const ids = fs
  .readdirSync(nbDir)
  .filter((f) => /^[A-D]\d\.ipynb$/.test(f))
  .map((f) => f.replace(".ipynb", ""))
  .sort();

const map = {};
let totalBytes = 0;
for (const id of ids) {
  const nb = JSON.parse(fs.readFileSync(path.join(nbDir, `${id}.ipynb`), "utf8"));
  const code = nb.cells.find((c) => c.cell_type === "code");
  const outs = code?.outputs ?? [];

  // printed text (stdout stream)
  const stdout = outs
    .filter((o) => o.output_type === "stream")
    .map((o) => (Array.isArray(o.text) ? o.text.join("") : o.text))
    .join("")
    .replace(/\s+$/, "");

  // the figure (first PNG in display_data / execute_result)
  const imgB64 = outs
    .map((o) => o.data?.["image/png"])
    .find(Boolean);
  let image = false;
  if (imgB64) {
    const buf = Buffer.from(Array.isArray(imgB64) ? imgB64.join("") : imgB64, "base64");
    fs.writeFileSync(path.join(imgDir, `${id}.png`), buf);
    totalBytes += buf.length;
    image = true;
  }
  map[id] = { stdout, image };
}

const ts =
  `// AUTO-GENERATED by scripts/gen-outputs.mjs from the executed notebooks.\n` +
  `// Each lesson's runnable snippet output: printed stdout + whether a figure\n` +
  `// (public/code-output/<id>.png) exists. Shown inline on the lesson page.\n` +
  `export const codeOutputs: Record<string, { stdout: string; image: boolean }> = ${JSON.stringify(map, null, 2)};\n`;
fs.writeFileSync(path.join(root, "src/lib/curriculum/codeOutputs.ts"), ts);

console.log(`wrote ${ids.length} outputs (${(totalBytes / 1024).toFixed(0)} KB of figures) + codeOutputs.ts`);
